### ISSUE TITLE
Installing log on Mac OS 10.13.6

### ISSUE THREAD

**Issue by lroffia** [arces-wot/SEPA-python3-APIs#10]
Please have a look at the following. Some errors are generated on: **sudo python setup.py install**

/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to sepy.egg-info/requires.txt
writing sepy.egg-info/PKG-INFO
writing top-level names to sepy.egg-info/top_level.txt
writing dependency_links to sepy.egg-info/dependency_links.txt
reading manifest file 'sepy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.jsap' anywhere in distribution
writing manifest file 'sepy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.13-intel/egg
running install_lib
running build_py
creating build/bdist.macosx-10.13-intel
creating build/bdist.macosx-10.13-intel/egg
creating build/bdist.macosx-10.13-intel/egg/sepy
copying build/lib/sepy/ConnectionHandler.py -> build/bdist.macosx-10.13-intel/egg/sepy
creating build/bdist.macosx-10.13-intel/egg/sepy/tests
copying build/lib/sepy/tests/__init__.py -> build/bdist.macosx-10.13-intel/egg/sepy/tests
copying build/lib/sepy/tests/SepyTestUnsecure_SAP.py -> build/bdist.macosx-10.13-intel/egg/sepy/tests
copying build/lib/sepy/tests/test.ysap -> build/bdist.macosx-10.13-intel/egg/sepy/tests
copying build/lib/sepy/SAPObject.py -> build/bdist.macosx-10.13-intel/egg/sepy
copying build/lib/sepy/__init__.py -> build/bdist.macosx-10.13-intel/egg/sepy
copying build/lib/sepy/ysap_template.sap -> build/bdist.macosx-10.13-intel/egg/sepy
copying build/lib/sepy/SEPA.py -> build/bdist.macosx-10.13-intel/egg/sepy
copying build/lib/sepy/Exceptions.py -> build/bdist.macosx-10.13-intel/egg/sepy
copying build/lib/sepy/tablaze.py -> build/bdist.macosx-10.13-intel/egg/sepy
byte-compiling build/bdist.macosx-10.13-intel/egg/sepy/ConnectionHandler.py to ConnectionHandler.pyc
  File "build/bdist.macosx-10.13-intel/egg/sepy/ConnectionHandler.py", line 224
    nonlocal subid
                 ^
**SyntaxError: invalid syntax**

byte-compiling build/bdist.macosx-10.13-intel/egg/sepy/tests/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.13-intel/egg/sepy/tests/SepyTestUnsecure_SAP.py to SepyTestUnsecure_SAP.pyc
  File "build/bdist.macosx-10.13-intel/egg/sepy/tests/SepyTestUnsecure_SAP.py", line 78
    nonlocal notif_counter
                         ^
**SyntaxError: invalid syntax**

byte-compiling build/bdist.macosx-10.13-intel/egg/sepy/SAPObject.py to SAPObject.pyc
  File "build/bdist.macosx-10.13-intel/egg/sepy/SAPObject.py", line 294
    print(sapFileString,file=destination_file)
                            ^
**SyntaxError: invalid syntax**

byte-compiling build/bdist.macosx-10.13-intel/egg/sepy/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.13-intel/egg/sepy/SEPA.py to SEPA.pyc
  File "build/bdist.macosx-10.13-intel/egg/sepy/SEPA.py", line 80
    print(json.dumps(jresults),file=fileDest)
                                   ^
**SyntaxError: invalid syntax**

byte-compiling build/bdist.macosx-10.13-intel/egg/sepy/Exceptions.py to Exceptions.pyc
byte-compiling build/bdist.macosx-10.13-intel/egg/sepy/tablaze.py to tablaze.pyc
  File "build/bdist.macosx-10.13-intel/egg/sepy/tablaze.py", line 105
    print(output,file=destination)
                     ^
**SyntaxError: invalid syntax**

creating build/bdist.macosx-10.13-intel/egg/EGG-INFO
copying sepy.egg-info/PKG-INFO -> build/bdist.macosx-10.13-intel/egg/EGG-INFO
copying sepy.egg-info/SOURCES.txt -> build/bdist.macosx-10.13-intel/egg/EGG-INFO
copying sepy.egg-info/dependency_links.txt -> build/bdist.macosx-10.13-intel/egg/EGG-INFO
copying sepy.egg-info/not-zip-safe -> build/bdist.macosx-10.13-intel/egg/EGG-INFO
copying sepy.egg-info/requires.txt -> build/bdist.macosx-10.13-intel/egg/EGG-INFO
copying sepy.egg-info/top_level.txt -> build/bdist.macosx-10.13-intel/egg/EGG-INFO
creating dist
creating 'dist/sepy-0.3-py2.7.egg' and adding 'build/bdist.macosx-10.13-intel/egg' to it
removing 'build/bdist.macosx-10.13-intel/egg' (and everything under it)
Processing sepy-0.3-py2.7.egg
creating /Library/Python/2.7/site-packages/sepy-0.3-py2.7.egg
Extracting sepy-0.3-py2.7.egg to /Library/Python/2.7/site-packages
  File "/Library/Python/2.7/site-packages/sepy-0.3-py2.7.egg/sepy/ConnectionHandler.py", line 224
    nonlocal subid
                 ^
**SyntaxError: invalid syntax**

  File "/Library/Python/2.7/site-packages/sepy-0.3-py2.7.egg/sepy/SAPObject.py", line 294
    print(sapFileString,file=destination_file)
                            ^
**SyntaxError: invalid syntax**

  File "/Library/Python/2.7/site-packages/sepy-0.3-py2.7.egg/sepy/SEPA.py", line 80
    print(json.dumps(jresults),file=fileDest)
                                   ^
**SyntaxError: invalid syntax**

  File "/Library/Python/2.7/site-packages/sepy-0.3-py2.7.egg/sepy/tablaze.py", line 105
    print(output,file=destination)
                     ^
SyntaxError: invalid syntax

  File "/Library/Python/2.7/site-packages/sepy-0.3-py2.7.egg/sepy/tests/SepyTestUnsecure_SAP.py", line 78
    nonlocal notif_counter
                         ^
**SyntaxError: invalid syntax**

Adding sepy 0.3 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/sepy-0.3-py2.7.egg
Processing dependencies for sepy==0.3
Searching for pyyaml
Reading https://pypi.python.org/simple/pyyaml/
Best match: PyYAML 4.2b4
Downloading https://files.pythonhosted.org/packages/a8/c6/a8d1555e795dbd0375c3c93b576ca13bbf139db51ea604afa19a2c35fc03/PyYAML-4.2b4.tar.gz#sha256=3c17fb92c8ba2f525e4b5f7941d850e7a48c3a59b32d331e2502a3cdc6648e76
Processing PyYAML-4.2b4.tar.gz
Writing /tmp/easy_install-tLEq1M/PyYAML-4.2b4/setup.cfg
Running PyYAML-4.2b4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tLEq1M/PyYAML-4.2b4/egg-dist-tmp-TPSdjV
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: **UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
In file included from ext/_yaml.c:565:
ext/_yaml.h:2:10: fatal error: 'yaml.h' file not found
#include <yaml.h>
         ^
1 error generated.
Error compiling module, falling back to pure Python**
zip_safe flag not set; analyzing archive contents...
Copying PyYAML-4.2b4-py2.7-macosx-10.13-intel.egg to /Library/Python/2.7/site-packages
Adding PyYAML 4.2b4 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/PyYAML-4.2b4-py2.7-macosx-10.13-intel.egg
Searching for prettytable
Reading https://pypi.python.org/simple/prettytable/
Best match: prettytable 0.7.2
Downloading https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2#sha256=853c116513625c738dc3ce1aee148b5b5757a86727e67eff6502c7ca59d43c36
Processing prettytable-0.7.2.tar.bz2
Writing /tmp/easy_install-5XmQ5o/prettytable-0.7.2/setup.cfg
Running prettytable-0.7.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5XmQ5o/prettytable-0.7.2/egg-dist-tmp-c6hnII
zip_safe flag not set; analyzing archive contents...
Copying prettytable-0.7.2-py2.7.egg to /Library/Python/2.7/site-packages
Adding prettytable 0.7.2 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/prettytable-0.7.2-py2.7.egg
Searching for argparse==1.4.0
Best match: argparse 1.4.0
Adding argparse 1.4.0 to easy-install.pth file

Using /Library/Python/2.7/site-packages
Searching for websocket-client==0.47.0
Best match: websocket-client 0.47.0
websocket-client 0.47.0 is already the active version in easy-install.pth

Using /Library/Python/2.7/site-packages
Searching for six==1.4.1
Best match: six 1.4.1
Adding six 1.4.1 to easy-install.pth file

Using /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
Finished processing dependencies for sepy==0.3

**Comment by fr4ncidir** [comment]
Yes this is an error of the readme. The target is python *version >=3 *

**Comment by fr4ncidir** [comment]
Now it should be better explained from readme (branch dev). Reopen the issue, if something goes wrong again.
