### ISSUE TITLE
Subscription handlers missing information

### ISSUE THREAD

**Issue by fr4ncidir** [arces-wot/SEPA-python3-APIs#2]
Subscription handler has no idea of what is its own subid. This is useful if you need just one notification and then unsubscribe from the handler itself

**Comment by desmovalvo** [comment]
Yes, right annotation. BTW I think that the entire subscription handling should be rewritten. Hopefully within the end of the week.

**Comment by lroffia** [comment]
Can be the "alias" member useful in this sense? Or maybe I did not get your
comment.

2018-01-08 17:36 GMT+01:00 Fabio Viola <notifications@github.com>:

**Comment by desmovalvo** [comment]
Yes. However in one of my experimental branch I should have an implemented version of subscription handler with subid&alias... Let me just check...
