### ISSUE TITLE
Multiline sparql

### ISSUE THREAD

**Issue by fr4ncidir** [arces-wot/SEPA-python3-APIs#4]
In [https://codebeautify.org/yaml-validator/](url) gli SPARQL multilinea vengono accettati solo facendo così:

```
sparql: >     
     "SELECT ?a ?b ?c    
      WHERE {?a ?b ?c}"
```

se non metti '>', dà errore

**Comment by desmovalvo** [comment]
It is a valid YAML. There are multiple ways to express a multi-line string. One is to enclose it in double quotes. Another way is to use ">" or "|" that are respectively known as "folded" or "literal" styles. Each of them provides a different way to escape special characters. However, double quotes should be fine (try [yamllint](http://www.yamllint.com/)). Correct me if I am wrong.

**Comment by desmovalvo** [comment]
Look at Steve Bennett's reply on [stackoverflow](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines)
