### ISSUE TITLE
Installation failed: readme.rd is missing

### ISSUE THREAD

**Issue by lroffia** [arces-wot/SEPA-python3-APIs#9]
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    with open("README.md","r") as fh:
IOError: [Errno 2] No such file or directory: 'README.md'

**Comment by fr4ncidir** [comment]
While I investigate, try this from the root folder of the repository
```
sudo python3 setup.py build
sudo python3 setup.py sdist
sudo python3 setup.py install
```

**Comment by lroffia** [comment]
Thank you. From the root no errors or warning are raised. I am attaching the installation log for you convenience:

PandaMacBook:SEPA-python3-APIs luca$ sudo python3 setup.py build
Password:
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running build
running build_py
running egg_info
writing sepy.egg-info/PKG-INFO
writing dependency_links to sepy.egg-info/dependency_links.txt
writing requirements to sepy.egg-info/requires.txt
writing top-level names to sepy.egg-info/top_level.txt
reading manifest file 'sepy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.jsap' anywhere in distribution
writing manifest file 'sepy.egg-info/SOURCES.txt'
PandaMacBook:SEPA-python3-APIs luca$ sudo python3 setup.py sdist
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running sdist
running egg_info
writing sepy.egg-info/PKG-INFO
writing dependency_links to sepy.egg-info/dependency_links.txt
writing requirements to sepy.egg-info/requires.txt
writing top-level names to sepy.egg-info/top_level.txt
reading manifest file 'sepy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.jsap' anywhere in distribution
writing manifest file 'sepy.egg-info/SOURCES.txt'
running check
creating sepy-0.3
creating sepy-0.3/dist
creating sepy-0.3/dist/sepy-0.3
creating sepy-0.3/dist/sepy-0.3/build
creating sepy-0.3/dist/sepy-0.3/build/lib
creating sepy-0.3/dist/sepy-0.3/build/lib/sepy
creating sepy-0.3/dist/sepy-0.3/build/lib/sepy/tests
creating sepy-0.3/dist/sepy-0.3/sepy
creating sepy-0.3/dist/sepy-0.3/sepy/tests
creating sepy-0.3/sepy
creating sepy-0.3/sepy.egg-info
creating sepy-0.3/sepy/tests
copying files to sepy-0.3...
copying MANIFEST.in -> sepy-0.3
copying README.rst -> sepy-0.3
copying setup.py -> sepy-0.3
copying dist/sepy-0.3/build/lib/sepy/ysap_template.sap -> sepy-0.3/dist/sepy-0.3/build/lib/sepy
copying dist/sepy-0.3/build/lib/sepy/tests/test.ysap -> sepy-0.3/dist/sepy-0.3/build/lib/sepy/tests
copying dist/sepy-0.3/sepy/ysap_template.sap -> sepy-0.3/dist/sepy-0.3/sepy
copying dist/sepy-0.3/sepy/tests/test.ysap -> sepy-0.3/dist/sepy-0.3/sepy/tests
copying sepy/ConnectionHandler.py -> sepy-0.3/sepy
copying sepy/Exceptions.py -> sepy-0.3/sepy
copying sepy/SAPObject.py -> sepy-0.3/sepy
copying sepy/SEPA.py -> sepy-0.3/sepy
copying sepy/__init__.py -> sepy-0.3/sepy
copying sepy/tablaze.py -> sepy-0.3/sepy
copying sepy/ysap_template.sap -> sepy-0.3/sepy
copying sepy.egg-info/PKG-INFO -> sepy-0.3/sepy.egg-info
copying sepy.egg-info/SOURCES.txt -> sepy-0.3/sepy.egg-info
copying sepy.egg-info/dependency_links.txt -> sepy-0.3/sepy.egg-info
copying sepy.egg-info/not-zip-safe -> sepy-0.3/sepy.egg-info
copying sepy.egg-info/requires.txt -> sepy-0.3/sepy.egg-info
copying sepy.egg-info/top_level.txt -> sepy-0.3/sepy.egg-info
copying sepy/tests/SepyTestUnsecure_SAP.py -> sepy-0.3/sepy/tests
copying sepy/tests/__init__.py -> sepy-0.3/sepy/tests
copying sepy/tests/test.ysap -> sepy-0.3/sepy/tests
Writing sepy-0.3/setup.cfg
Creating tar archive
removing 'sepy-0.3' (and everything under it)
PandaMacBook:SEPA-python3-APIs luca$ sudo python3 setup.py install
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing sepy.egg-info/PKG-INFO
writing dependency_links to sepy.egg-info/dependency_links.txt
writing requirements to sepy.egg-info/requires.txt
writing top-level names to sepy.egg-info/top_level.txt
reading manifest file 'sepy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.jsap' anywhere in distribution
writing manifest file 'sepy.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/sepy
copying build/lib/sepy/ConnectionHandler.py -> build/bdist.macosx-10.9-x86_64/egg/sepy
creating build/bdist.macosx-10.9-x86_64/egg/sepy/tests
copying build/lib/sepy/tests/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/sepy/tests
copying build/lib/sepy/tests/SepyTestUnsecure_SAP.py -> build/bdist.macosx-10.9-x86_64/egg/sepy/tests
copying build/lib/sepy/tests/test.ysap -> build/bdist.macosx-10.9-x86_64/egg/sepy/tests
copying build/lib/sepy/SAPObject.py -> build/bdist.macosx-10.9-x86_64/egg/sepy
copying build/lib/sepy/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/sepy
copying build/lib/sepy/ysap_template.sap -> build/bdist.macosx-10.9-x86_64/egg/sepy
copying build/lib/sepy/SEPA.py -> build/bdist.macosx-10.9-x86_64/egg/sepy
copying build/lib/sepy/Exceptions.py -> build/bdist.macosx-10.9-x86_64/egg/sepy
copying build/lib/sepy/tablaze.py -> build/bdist.macosx-10.9-x86_64/egg/sepy
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sepy/ConnectionHandler.py to ConnectionHandler.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sepy/tests/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sepy/tests/SepyTestUnsecure_SAP.py to SepyTestUnsecure_SAP.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sepy/SAPObject.py to SAPObject.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sepy/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sepy/SEPA.py to SEPA.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sepy/Exceptions.py to Exceptions.cpython-36.pyc
byte-compiling build/bdist.macosx-10.9-x86_64/egg/sepy/tablaze.py to tablaze.cpython-36.pyc
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying sepy.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying sepy.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying sepy.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying sepy.egg-info/not-zip-safe -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying sepy.egg-info/requires.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying sepy.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
creating 'dist/sepy-0.3-py3.6.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing sepy-0.3-py3.6.egg
creating /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sepy-0.3-py3.6.egg
Extracting sepy-0.3-py3.6.egg to /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Removing sepy 0.2 from easy-install.pth file
Adding sepy 0.3 to easy-install.pth file

Installed /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sepy-0.3-py3.6.egg
Processing dependencies for sepy==0.3
Searching for PyYAML==3.13
Best match: PyYAML 3.13
Adding PyYAML 3.13 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for prettytable==0.7.2
Best match: prettytable 0.7.2
Processing prettytable-0.7.2-py3.6.egg
prettytable 0.7.2 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/prettytable-0.7.2-py3.6.egg
Searching for argparse==1.4.0
Best match: argparse 1.4.0
Processing argparse-1.4.0-py3.6.egg
argparse 1.4.0 is already the active version in easy-install.pth

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/argparse-1.4.0-py3.6.egg
Searching for websocket-client==0.47.0
Best match: websocket-client 0.47.0
Adding websocket-client 0.47.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Finished processing dependencies for sepy==0.3
